/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hent kaffemeny
         * @description Returnerer en liste over alle tilgjengelige kaffedrikker i kaffebaren.
         */
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hent bestillinger
         * @description Returnerer bestillinger, nyeste først. Kan filtreres på status og pagineres
         *     med `limit` og `offset`.
         */
        get: operations["listOrders"];
        put?: never;
        /**
         * Opprett bestilling
         * @description Oppretter en ny bestilling med status `PENDING` og publiserer hendelsen
         *     `order.created` til RabbitMQ.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id-en til bestillingen. */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /** Hent én bestilling */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Oppdater status på en bestilling
         * @description Den anbefalte måten å endre status på. `PATCH` fordi vi oppdaterer én
         *     egenskap på ressursen, ikke erstatter hele den.
         *
         *     Publiserer `order.status-changed` til RabbitMQ.
         */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id-en til bestillingen. */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oppdater status på en bestilling (action-variant)
         * @description Alias for `PATCH /orders/{orderId}`. Finnes fordi oppgave 7 i samling 3 lot
         *     det være opp til hver deltaker om status skulle endres med `PUT`, `PATCH`
         *     eller et eget action-endepunkt. Begge de to vanligste variantene er støttet
         *     slik at en frontend kan peke på deltakerens eget API uten endringer.
         *
         *     `PATCH /orders/{orderId}` er anbefalingen.
         */
        post: operations["setOrderStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Helsesjekk
         * @description Brukes av Docker sin healthcheck. Svarer alltid `200` så lenge HTTP-serveren
         *     lever — status på RabbitMQ-tilkoblingen rapporteres i `rabbitmq`-feltet, men
         *     gjør ikke tjenesten usunn. API-et skal fungere selv om broker er nede.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Coffee
         * @description Representerer en kaffedrikk på menyen.
         */
        Coffee: {
            /**
             * Format: uuid
             * @example c0ffee01-0000-4000-8000-000000000001
             */
            id: string;
            /** @example Kaffe Latte */
            name: string;
            /**
             * @description Pris i norske kroner.
             * @example 52
             */
            price: number;
        };
        /**
         * OrderStatus
         * @description Livssyklusen til en bestilling. `PENDING` → `BREWING` → `READY`.
         * @example PENDING
         * @enum {string}
         */
        OrderStatus: "PENDING" | "BREWING" | "READY";
        /**
         * CoffeeSize
         * @example MEDIUM
         * @enum {string}
         */
        CoffeeSize: "SMALL" | "MEDIUM" | "LARGE";
        /**
         * MilkType
         * @example OAT
         * @enum {string}
         */
        MilkType: "WHOLE" | "SKIMMED" | "OAT" | "SOY";
        /**
         * CreateOrderRequest
         * @description Det kunden sender inn for å bestille.
         */
        CreateOrderRequest: {
            /**
             * Format: uuid
             * @description Id-en til en kaffe fra `GET /menu`.
             * @example c0ffee01-0000-4000-8000-000000000001
             */
            coffeeId: string;
            /**
             * @description Navnet bestillingen ropes opp på. Kan ikke være blankt.
             * @example Ada
             */
            customerName: string;
            size: components["schemas"]["CoffeeSize"];
            milkType?: components["schemas"]["MilkType"];
            /**
             * @description Ekstra shot espresso.
             * @example false
             */
            extraShot?: boolean;
            /**
             * @description Antall kopper i samme bestilling.
             * @default 1
             * @example 1
             */
            quantity: number;
        };
        /**
         * UpdateOrderStatusRequest
         * @description Et dedikert request-objekt som kun inneholder det som skal endres — ikke
         *     hele `Order`. Det gjør det umulig for en klient å ved et uhell skrive over
         *     `createdAt` eller `customerName`.
         */
        UpdateOrderStatusRequest: {
            status: components["schemas"]["OrderStatus"];
        };
        /**
         * Order
         * @description En bestilling slik serveren svarer med den.
         */
        Order: {
            /**
             * Format: uuid
             * @example 7f3f1f6e-9a0a-4e0c-9f5f-2f0a5a1d8b21
             */
            orderId: string;
            /**
             * Format: uuid
             * @example c0ffee01-0000-4000-8000-000000000001
             */
            coffeeId: string;
            /**
             * @description Denormalisert fra menyen, slik at en klient kan vise ordren uten et ekstra kall.
             * @example Kaffe Latte
             */
            coffeeName: string;
            /** @example Ada */
            customerName: string;
            size: components["schemas"]["CoffeeSize"];
            milkType?: components["schemas"]["MilkType"];
            /** @example false */
            extraShot?: boolean;
            /** @example 1 */
            quantity: number;
            status: components["schemas"]["OrderStatus"];
            /**
             * Format: date-time
             * @example 2026-09-13T09:41:12.004Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-09-13T09:41:20.118Z
             */
            updatedAt: string;
        };
        /**
         * Problem
         * @description Feilrespons etter RFC 7807 (Problem Details for HTTP APIs).
         *     Sendes med `Content-Type: application/problem+json`.
         */
        Problem: {
            /**
             * @description URI som identifiserer feiltypen.
             * @example https://codeacademy.soprasteria.no/problems/validation-error
             */
            type: string;
            /**
             * @description Kort, menneskelesbar oppsummering.
             * @example Ugyldig forespørsel
             */
            title: string;
            /** @example 400 */
            status: number;
            /**
             * @description Forklaring knyttet til akkurat denne forekomsten.
             * @example customerName må være minst 2 tegn
             */
            detail?: string;
            /**
             * @description Stien som feilet.
             * @example /orders
             */
            instance?: string;
            /** @description Feltene som ikke validerte. Kun ved 400. */
            errors?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /**
             * @description Feltet som feilet, som en peker inn i requesten.
             * @example customerName
             */
            field: string;
            /** @example must NOT have fewer than 2 characters */
            message: string;
        };
        /** Health */
        Health: {
            /** @enum {string} */
            status: "ok";
            /**
             * @description Tilstanden på broker-tilkoblingen. API-et fungerer uansett verdi.
             * @enum {string}
             */
            rabbitmq: "connected" | "disconnected" | "disabled";
            uptimeSeconds: number;
        };
    };
    responses: {
        /** @description Requesten var ugyldig. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Ressursen finnes ikke. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Id-en til bestillingen. */
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description En liste med kaffedrikker ble vellykket hentet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coffee"][];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description Returner kun bestillinger med denne statusen. */
                status?: components["schemas"]["OrderStatus"];
                /** @description Maks antall bestillinger i svaret. */
                limit?: number;
                /** @description Hvor mange bestillinger som skal hoppes over. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description En liste med bestillinger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Bestillingen ble opprettet. */
            201: {
                headers: {
                    /** @description URL-en til den opprettede bestillingen. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id-en til bestillingen. */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bestillingen ble funnet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id-en til bestillingen. */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Statusen ble oppdatert. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    setOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id-en til bestillingen. */
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Statusen ble oppdatert. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tjenesten lever. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
